"""initial_users

Revision ID: 2025_12_27_A
Revises: 
Create Date: 2025-12-27 15:40:39.890725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025_12_27_A'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('patronymic', sa.String(length=64), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('language', sa.String(length=32), server_default='RU', nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login', name='uq_users_login')
    )
    op.execute("""
    CREATE TRIGGER before_insert_user
    BEFORE INSERT ON users FOR EACH ROW
    BEGIN
        -- пока что просто обновляем время пользователя, впоследствии надо будет сохранять изменения в отдельную таблицу
        SET NEW.created_at = NOW();
        SET NEW.updated_at = NOW();
        
    END
    """)
    op.execute("""
    CREATE TRIGGER before_update_user
    BEFORE UPDATE ON users FOR EACH ROW
    BEGIN
        -- пока что просто обновляем время пользователя, впоследствии надо будет сохранять изменения в отдельную таблицу
        SET NEW.created_at = OLD.created_at;
        SET NEW.updated_at = NOW();
    
    END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS before_update_user")
    op.execute("DROP TRIGGER IF EXISTS before_insert_user")
    op.drop_table('users')
    # ### end Alembic commands ###
